# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Update Date

on:
  schedule:
    - cron: 0 0 1 1 *
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
    - name: Update year
      run: python update_date.py
    - name: Calculate Year
      id: calc_year
      run: echo "current_year=$(date '+%Y')\n" >> $GITHUB_OUTPUT
    - name: Commit & Push changes
      run: >
          git config --global user.name 'Update Date Bot'
          && git config --global user.email 'freemasen@users.noreply.github.com'
          && git add ./pre.rhai
          && git commit -m "update date to $(date '+%Y')"
          && git push
